
global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093"

rule_files:
  - "/opt/prometheus/alert.rules"

scrape_configs:
  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - "https://amazon.com"
          - "https://github.com"
          - "https://google.com"
          - "https://stackoverflow.com"
          - "https://www.mathrubhumi.com"
          - "https://www.manoramanews.com"
          - "https://www.binance.com"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115  # Blackbox Exporter
